set(RXS_OS_UNIX ON)
add_definitions(-DRXS_OS_UNIX)

if (ANDROID OR CMAKE_SYSTEM_NAME MATCHES "Android")
    set(RXS_OS_ANDROID ON)
    add_definitions(-DRXS_OS_ANDROID)
elseif (CMAKE_SYSTEM_NAME MATCHES "Linux")
    set(RXS_OS_LINUX ON)
    add_definitions(-DRXS_OS_LINUX)
elseif (CMAKE_SYSTEM_NAME STREQUAL FreeBSD OR CMAKE_SYSTEM_NAME STREQUAL DragonFly)
    set(RXS_OS_FREEBSD ON)
    add_definitions(-DRXS_OS_FREEBSD)
elseif (CMAKE_SYSTEM_NAME STREQUAL OpenBSD)
    set(RXS_OS_OPENBSD ON)
    add_definitions(-DRXS_OS_OPENBSD)
endif()

if (WITH_SECURE_JIT)
    add_definitions(-DRXS_SECURE_JIT)
endif()
