name: BSD build test

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

permissions:
  contents: read

jobs:
  build-bsd:
    name: Build rxs on freebsd
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build on freebsd
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          prepare: |
            pkg install -y git cmake libuv openssl hwloc gmake llvm19
          run: |
            mkdir -p build
            cd build
            cmake .. -DCMAKE_C_COMPILER=clang19 -DCMAKE_CXX_COMPILER=clang++19
            gmake -j$(sysctl -n kern.smp.cpus)
